language: ruby
script:
  - bundle exec rspec
jdk:
  - openjdk7
rvm:
  - 1.8.7
  - 2.1.5
  - ruby-head
  - rbx-2
  - jruby-head
allow_failures:
  - rvm: jruby-head
  - rvm: rbx-2
  - rvm: ruby-head
notifications:
  recipients:
    - brixen@gmail.com
