sudo: false
language: ruby
before_script:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS
  # https://github.com/travis-ci/travis-ci/issues/8978
  - gem update --system
script:
  - bundle exec rspec
matrix:
  include:
  - rvm: 2.2.9
  - rvm: 2.3.6
  - rvm: 2.4.3
  - rvm: 2.5.0
  - rvm: ruby-head
  - jdk: oraclejdk8
    install:
      - curl -L https://github.com/graalvm/truffleruby/releases/download/vm-enterprise-0.28/truffleruby-testing-0.28.tar.gz | tar xz
      - source truffleruby/setup_env
      - bundle install
