sudo: false
language: ruby
script:
  - bundle exec rspec
matrix:
  include:
  - rvm: 2.3.7
  - rvm: 2.4.4
    before_install:
      # https://github.com/travis-ci/travis-ci/issues/8978
      - gem update --system
      - gem install bundler
  - rvm: 2.5.1
    before_install:
      # https://github.com/travis-ci/travis-ci/issues/8978
      - gem update --system
      - gem install bundler
  - rvm: ruby-head
    before_install:
      # https://github.com/travis-ci/travis-ci/issues/8978
      - gem update --system
      - gem install bundler
  - rvm: system
    install:
      - export TRUFFLERUBY_VERSION=1.0.0-rc5
      - curl -L https://github.com/oracle/truffleruby/releases/download/vm-$TRUFFLERUBY_VERSION/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64.tar.gz | tar xz
      - export PATH="$PWD/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64/bin:$PATH"
      - gem install bundler
      - bundle install
